version: '3.8'

services:
  pgadmin9:
    image: registry.inventec/infra/dpage/pgadmin4:9.4
    container_name: pgadmin9
    ports:
      - "80:80"
    volumes:
      - /data/pgadmin4/pgadmin9:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "cobolbaby@qq.com"
      PGADMIN_DEFAULT_PASSWORD: "123456"
      GUNICORN_THREADS: "50"
      PGADMIN_CONFIG_MAX_LOGIN_ATTEMPTS: "10"
      PGADMIN_CONFIG_UPGRADE_CHECK_ENABLED: "False"
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "False"
      PGADMIN_LISTEN_ADDRESS: "0.0.0.0"
    restart: always
